### ISSUE TITLE
Just a hint

### ISSUE THREAD

**Issue by ich777** [techie2000/unraid#1]
Hi,
look at this over here... :)

https://github.com/ich777/un-get

**Comment by ich777** [comment]
Closed because no answer.

**Comment by techie2000** [comment]
hi @ich777 
I ran into a few problems with a corrupted usb at the same time as trying to add a DAS for future proofing, and other 'life 
'stuff' happened in the last month.

I've just taken a look at this and it works well 👍 
I thought I'd read somewhere that the use of /extras was not encouraged as a way of loading packages? Do you know if I imagined that, or I read it, but whilst not encouraged, is still acceptable?

**Comment by ich777** [comment]
@techie2000 It is not encouraged because if you don‘t know what you are doing you can have a system that is not working correctly or in the worst case not booting if you pick for instance the wrong package for the wrong Slackware version, that‘s why I also made the disclaimer that my tool is also only for advanced users because strictly speaking Unraid isn‘t a general purpose server and you should really run everything through Docker or a VM.
